{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Efimeral API",
    "description" : "This is the API that manages the creation of Linux containers on demand.",
    "contact" : {
      "email" : "arielgerardorios@gmail.com"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/ariel17/efimeral/1.0.0",
    "description" : "SwaggerHub API Auto Mocking"
  } ],
  "security" : [ {
    "bearerAuth" : [ ]
  } ],
  "paths" : {
    "/instances" : {
      "post" : {
        "summary" : "Creates a new Linux instance to expose in the web.",
        "description" : "Builds a new Linux instance and exposes the HTTP terminal service for ondemand usage until connection is closed.",
        "operationId" : "createInstance",
        "responses" : {
          "201" : {
            "description" : "Instance created.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/InstanceCreationResponse"
                }
              }
            }
          },
          "401" : {
            "description" : "Unauthorized."
          },
          "429" : {
            "description" : "Too many requests."
          }
        }
      }
    },
    "/instances/{instanceId}" : {
      "get" : {
        "summary" : "Obtains the status of a given instance ID, if it exists.",
        "description" : "TODO",
        "operationId" : "statusInstance",
        "parameters" : [ {
          "name" : "instanceId",
          "in" : "path",
          "description" : "Instance ID to fetch status from.",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string",
            "format" : "sha1",
            "example" : "09120402431e49c8ffdbbdb90e044431e2300de4"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Instance status description.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/InstanceStatusResponse"
                }
              }
            }
          },
          "401" : {
            "description" : "Unauthorized."
          },
          "404" : {
            "description" : "Instance not found."
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "InstanceCreationResponse" : {
        "required" : [ "id", "status" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "format" : "sha1",
            "example" : "09120402431e49c8ffdbbdb90e044431e2300de4"
          },
          "status" : {
            "type" : "string",
            "example" : "starting",
            "enum" : [ "starting", "failed" ]
          }
        }
      },
      "InstanceStatusResponse" : {
        "required" : [ "id", "status" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "format" : "sha1",
            "example" : "09120402431e49c8ffdbbdb90e044431e2300de4"
          },
          "status" : {
            "type" : "string",
            "example" : "[\"starting\",\"failed\",\"running\",\"destroying\",\"destroyed\"]"
          },
          "url" : {
            "type" : "string",
            "format" : "uri",
            "example" : "https://09120402431e49c8ffdbbdb90e044431e2300de4.efimeral.com:5566"
          }
        }
      }
    },
    "securitySchemes" : {
      "bearerAuth" : {
        "type" : "http",
        "scheme" : "bearer",
        "bearerFormat" : "JWT"
      }
    }
  }
}