{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Efimeral API",
    "description" : "This is the API that manages the creation of Linux containers on demand.",
    "contact" : {
      "email" : "arielgerardorios@gmail.com"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/ariel17/efimeral/1.0.0",
    "description" : "SwaggerHub API Auto Mocking"
  } ],
  "security" : [ {
    "bearerAuth" : [ ]
  } ],
  "paths" : {
    "/instances" : {
      "post" : {
        "summary" : "Creates a new Linux instance to expose in the web.",
        "description" : "Builds a new Linux instance and exposes the HTTP terminal service for ondemand usage until connection is closed.",
        "operationId" : "createInstance",
        "responses" : {
          "201" : {
            "description" : "Instance created.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Instance"
                }
              }
            }
          },
          "401" : {
            "description" : "Unauthorized."
          },
          "429" : {
            "description" : "Too many requests."
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "Instance" : {
        "required" : [ "id" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "format" : "sha1",
            "example" : "09120402431e49c8ffdbbdb90e044431e2300de4"
          },
          "url" : {
            "type" : "string",
            "format" : "uri",
            "example" : "https://09120402431e49c8ffdbbdb90e044431e2300de4.efimeral.com:5566"
          },
          "createdAt" : {
            "type" : "string",
            "format" : "date-time",
            "example" : "2016-08-29T09:12:33.001Z"
          }
        }
      }
    },
    "securitySchemes" : {
      "bearerAuth" : {
        "type" : "http",
        "scheme" : "bearer",
        "bearerFormat" : "JWT"
      }
    }
  }
}